# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-gateway-ingress
#   namespace: backend
# spec:
#   podSelector:
#     matchLabels:
#       app: backend
#   ingress:
#   - from:
#     - ipBlock:
#         cidr: 10.10.0.0/16  # CIDR of gateway VPC
#     ports:
#     - protocol: TCP
#       port: 80
#   policyTypes:
#   - Ingress
